version: '3.7'

services:
  eventstore.db:
    image: eventstore/eventstore:21.10.9-buster-slim
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - '1113:1113'
      - '2113:2113'
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /c/data/eventstore/data
      - type: volume
        source: eventstore-volume-logs
        target: /c/data/eventstore/logs
    networks:
      - events

  pg.db:
    image: postgres:12.13-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080  
    networks:
      - db
  
  calc-shared:
    build:
      context: calc-shared

  calc-api:
    build:
      context: calc-api
    environment:
      - DATABASE_URL=postgresql://root:example@calc-event-sourcing-pg.db-1:5432/mydb?schema=public
      - ESDB_CONNECTION_STRING=esdb://calc-event-sourcing-eventstore.db-1:2113?tls=false
    ports:
      - 3000:3000
    networks:
      - db
      - events

  calc-worker:
    build:
      context: calc-worker
    environment:
      - ESDB_CONNECTION_STRING=esdb://calc-event-sourcing-eventstore.db-1:2113?tls=false
    networks:
      - events

volumes:
  eventstore-volume-data:
  eventstore-volume-logs:
  pg-data:

networks:
  events:
  db: